# 
# Docker file to create the image to run PSS (Panosc Search Scoring)
#
# use python3.9 container
FROM python:3.9

# create app folder
RUN mkdir /app
# copy our application
COPY app /app/app
# copy unittest
COPY test /app/test

# copy script to download stopwords
COPY download_nltk_stopwords.py /app/.
# copy python requirements (for api and test)
COPY requirements.txt /app/requirements.txt

WORKDIR /app

# install python requirements
RUN pip install --no-cache-dir -r /app/requirements.txt

# now downloads the NLTK stopwords
RUN python download_nltk_stopwords.py

CMD ["pytest", "test"]
